theme: jekyll-theme-chirpy

lang: en
timezone: America/Sao_Paulo

title: g0ttfrid
tagline: offensive security
description:
url: "https://g0ttfrid.github.io"

github:
  username: g0ttfrid

twitter:
  username: g0ttfrid

social:
  name: g0ttfrid
  email: ""
  links:
    - https://twitter.com/g0ttfrid
    - https://github.com/g0ttfrid
    - https://linkedin.com/in/yurimaia

theme_mode: dark

avatar: assets/img/avatar.png

toc: true

comments:
  provider:

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
